services:
  menu_builder.admin.menu:
    class: MenuBuilderBundle\Admin\MenuAdmin
    arguments:
      - ~
      - MenuBuilderBundle\Entity\Menu
      - ~
    tags:
      - { name: sonata.admin, manager_type: orm, group: "menu_builder.admin.group", label: "menu_builder.admin.group.menu" }
    calls:
      - [ setTranslationDomain, [MenuBuilderBundle] ]

  menu_builder.admin.menu_item:
    class: MenuBuilderBundle\Admin\MenuItemAdmin
    arguments:
      - ~
      - MenuBuilderBundle\Entity\MenuItem
      - MenuBuilderBundle:Admin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "menu_builder.admin.group", label: "menu_builder.admin.group.menu_item", show_in_dashboard: false }
    calls:
      - [ setTranslationDomain, [MenuBuilderBundle] ]
